// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYAVsIcLvEmSTMWIGddkHIdH1LXmw0dv4',
    appId: '1:1008292895901:android:5b24131db287b3041a4874',
    messagingSenderId: '1008292895901',
    projectId: 'simple-chat-13451',
    storageBucket: 'simple-chat-13451.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPzYhA8WCmidlelkILX3nUukZ_Xp3h9b0',
    appId: '1:1008292895901:ios:8526c98c429779ff1a4874',
    messagingSenderId: '1008292895901',
    projectId: 'simple-chat-13451',
    storageBucket: 'simple-chat-13451.firebasestorage.app',
    androidClientId: '1008292895901-vf0t435jnkbq729427o1t2pqvas85g0n.apps.googleusercontent.com',
    iosClientId: '1008292895901-tookdpt7up6c7upp4iqoviks1pie1lin.apps.googleusercontent.com',
    iosBundleId: 'com.example.simpleChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPzYhA8WCmidlelkILX3nUukZ_Xp3h9b0',
    appId: '1:1008292895901:ios:8526c98c429779ff1a4874',
    messagingSenderId: '1008292895901',
    projectId: 'simple-chat-13451',
    storageBucket: 'simple-chat-13451.firebasestorage.app',
    iosBundleId: 'com.example.simpleChat',
  );
}